### ISSUE TITLE
ecma 6 support 

### ISSUE THREAD

**Issue by kobiv** [jdanyow/aurelia-plunker#1]
i am trying to use ecma 6 modules and it doesn't work 
look at the following plunker example :

http://run.plnkr.co/a4ZhJcg0R1ZDTFKJ/#/

choose HtmlGrid it doesnt load the ecma6 modules

**Comment by jdanyow** [comment]
is your plunker private?  when I click on the link I can't access it

**Comment by kobiv** [comment]
http://run.plnkr.co/plunks/yHzFoi/

try it now

**Comment by jdanyow** [comment]
that got me here: ![plunker](http://i.imgur.com/l7YQGco.png) but with no link to view the editable plunker

**Comment by kobiv** [comment]
sorry again 
here is the link

http://plnkr.co/edit/zoGl6a

**Comment by jdanyow** [comment]
Got it this time- so when I run that plunker, there's an error right away:

```json
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "Payload content length greater than maximum allowed: 1048576"
}
```

**Comment by kobiv** [comment]
fixed

**Comment by jdanyow** [comment]
ok I can view it now, and run the app, and the grid displays.  

What is the issue?

**Comment by kobiv** [comment]
you can close the issue 
it was a problem with the plunker thanks for your help
