### ISSUE TITLE
Update bundled Aurelia to 1.0.x

### ISSUE THREAD

**Issue by dmikrot** [jdanyow/aurelia-plunker#9]
The included Aurelia libraries are out of date. It would be nice to have an updated Plunker now that Aurelia is out of beta.

Was trying to create a plunker to reproduce [a bug](http://stackoverflow.com/questions/38763698/how-to-use-layouts-in-aurelia) with [Aurelia Router Layouts](http://aurelia.io/hub.html#/doc/article/aurelia/router/latest/router-configuration/10), but I couldn't get the layout to work at all in [my plunker](http://plnkr.co/edit/kTgEzJdmlS5W2ss6uHsL?p=preview). Not sure what's causing the problem, could be something wrong with my router config, but it all looked correct to me. I updated to the latest release of aurelia-plunker (v.11.10) but that didn't fix anything.

**Comment by jdanyow** [comment]
Use this: https://gist.run/?id=7542e061bc940cde506b, it's has the latest bits. I'll add a deprecation notice to this repo.
